### ISSUE TITLE
Can you share the raw dataset?

### ISSUE THREAD

**Issue by ahmed-hassan19** [mohamedebrahim96/Dostor#1]
Can you share the raw dataset, please?
I am working on a research project and I need the raw source data of your application.
I will cite your work in the paper isA.

**Comment by mohamedebrahim96** [comment]
You can find it in the source code

**Comment by mohamedebrahim96** [comment]
I don't have the raw dataset.
I scrapped all of the data from the official website of Egypt constitution.
http://dostour.eg

**Comment by ahmed-hassan19** [comment]
I would do that too, but it seems this website isn't available anymore "The service is unavailable.".
Thank you anyways, and great job btw!
